from django.urls import path
from .views import *

urlpatterns = [
    path("tools/pdf-to-word", PDFToWordView.as_view(), name="pdf-to-word"),
    path("tools/csv-file-to-sql", CSVFileToSQLView.as_view(), name="csv-file-to-sql"),
    path("tools/csv-text-to-sql", CSVTextToSQLView.as_view(), name="csv-text-to-sql"),
    path("tools/csv-file-to-json", CSVFileToJSONView.as_view(), name="csv-file-to-json"),
    path("tools/csv-text-to-json", CSVTextToJSONView.as_view(), name="csv-text-to-json"),
    path('tools/csv-text-to-excel',         CSVTextToExcelView.as_view(),  name='csv-text-to-excel'),
    path('tools/csv-file-to-excel',    CSVFileToExcelView.as_view(),  name='csv-file-to-excel'),
    path('tools/json-file-to-csv',  JSONFileToCSVView.as_view(), name='json-file-to-csv'),
    path('tools/json-text-to-csv',  JSONTextToCSVView.as_view(), name='json-text-to-csv'),
    path('tools/excel-to-csv', ExcelToCSVView.as_view(), name='excel-to-csv'),
    path('tools/json-text-to-excel',       JSONTextToExcelView.as_view(), name='json-text-to-excel'),
    path('tools/json-file-to-excel',  JSONFileToExcelView.as_view(), name='json-file-to-excel'),

    path("tools/pdf-to-jpg", PDFToJPGView.as_view(), name="pdf-to-jpg"),
    path("tools/pdf-to-excel", PDFToExcelView.as_view(), name="pdf-to-excel"),
    path("tools/word-to-pdf", WordToPDFView.as_view(), name="word-to-pdf"),
    path("tools/pdf-encrypt", EncryptPDFView.as_view(), name="pdf-encrypt"),
    path("tools/pdf-decrypt", DecryptPDFView.as_view(), name="pdf-decrypt"),
     path('tools/pdf-compress',             CompressPDFView.as_view(),     name='pdf-compress'),
     path('tools/pdf-to-png',          PDFToPNGView.as_view(),        name='pdf-to-png'),
    path("tools/pdf-info", PDFInfoView.as_view(), name="pdf-info"),
    path('tools/pdf-rotate',               RotatePDFView.as_view(),       name='pdf-rotate'),
    path('tools/pdf-pages',                PDFPageInfoView.as_view(),     name='pdf-pages'), 
    path('tools/pdf-watermark',            WatermarkPDFView.as_view(),    name='pdf-watermark'),
    path('tools/format-json-file',         JSONFileFormatterView.as_view(), name='json-file-formatter'),
    path('tools/format-json-text',         JSONTextFormatterView.as_view(), name='json-text-formatter'),
    path('tools/ocr-pdf',             OCRPDFView.as_view(),       name='pdf-compress'),
    path('tools/timestamp',          TimestampConverterView.as_view(),name='timestamp-converter'),
    path('tools/timestamp/batch',    TimestampBatchView.as_view(),    name='timestamp-batch'),

    path('tools/base64-encode-text',  Base64EncodeTextView.as_view(),  name='base64-encode-text'),
    path('tools/base64-encode-file',  Base64EncodeFileView.as_view(),  name='base64-encode-file'),
    path('tools/base64-decode',       Base64DecodeView.as_view(),      name='base64-decode'),
    path('tools/base64-validate',     Base64ValidateView.as_view(),    name='base64-validate'),
    path('tools/uuid-generate',       UUIDGeneratorView.as_view(),     name='uuid-generate'),
    path('tools/uuid-validate',       UUIDValidateView.as_view(),      name='uuid-validate'),
    path('tools/uuid-bulk',           UUIDBulkView.as_view(),          name='uuid-bulk'),
    path('tools/file-encrypt',            FileEncryptView.as_view(),       name='file-encrypt'),
    path('tools/file-decrypt',            FileDecryptView.as_view(),       name='file-decrypt'),
    path('tools/file-hash',               FileHashView.as_view(),          name='file-hash'),
    path('tools/password-generate',       PasswordGeneratorView.as_view(),  name='password-generate'),
    path('tools/password-strength',       PasswordStrengthView.as_view(),   name='password-strength'),
    path('tools/passphrase-generate',     PassphraseGeneratorView.as_view(),name='passphrase-generate'),
    path('tools/hash-generate',           HashGeneratorView.as_view(),      name='hash-generate'),
    path('tools/hash-compare',            HashCompareView.as_view(),        name='hash-compare'),
    path('tools/file-checksum',           FileChecksumView.as_view(),       name='file-checksum'),
    path('tools/word-to-jpg',           WordToJPGView.as_view(),          name='word-to-jpg'),
    path('tools/word-to-txt',           WordToTXTView.as_view(),          name='word-to-txt'),
    path('tools/txt-to-word',           TXTToWordView.as_view(),          name='txt-to-word'),
    path('tools/merge-docx',              MergeDOCXView.as_view(),          name='merge-docx'),
    path('tools/split-docx',              SplitDOCXView.as_view(),          name='split-docx'), 
    path('tools/text-compare',    TextCompareView.as_view(),  name='text-compare'),
    path('tools/file-compare',    FileCompareView.as_view(),  name='file-compare'),
    path('tools/pdf-merge', MergePDFView.as_view(), name='pdf-merge'),
    path('tools/pdf-split', SplitPDFView.as_view(), name='pdf-split'),
    path("health/", HealthCheckView.as_view(), name="health-check"),
    
]
